### ISSUE TITLE
GetpPrivateApplicationDataLocation issue

### ISSUE THREAD

**Issue by rgleason** [rgleason/celestial_navigation_pi#14]
```
PS
As there is no way to write issues for the celestial_navigation_pi plugin, and knowing that you develop it too, I inform you that the same problem exists for it
to obtain that celestial_navigation create the good path inside flatpak :
/home/yourusername/.var/app/org.opencpn.OpenCPN/config/opencpn/plugins/ celestial_navigation
where to store the personnal writeable Sights.xml file

```

**Comment by rgleason** [comment]
Dave,  I've found two files that are needed, plus added zlib-1.2.3 and bzip2 files which were also missing since there were errors looking for these.  What I have done so far:

1. Found zuFile.h and zuFile.cpp on Climatology added  them to Celestial_Nav  /src/ folder.  Then added paths in CmakeLists.txt under set SRC and set HDRS.  These files were from zygrib grib viewer.
2.  Found libs/bzip2 on Weather_routing  bzip2 and added that to Cel_Nav libs/ folder (has a cmakelists.txt file, and have added the necessary text to  the "If not Flatpak" statement to include bzip2 files.
4. Found zlib-1.2.3 and added that to  libs\zlib-1.2.3\include  the two files are zlib.h and zconf.h  Then added an include statement.
5. I believe these files are all found now during build.  
6. What is happening now is I am getting a  fatal error from  CelestialNavigaionDialog.cpp at line 625.

`C:\Users\fcgle\source\celestial_navigation_pi\src\CelestialNavigationDialog.cpp(625): fatal error C1004: unexpected end-of-file found [C:\Users\fcgle\source\celestial_navigation_pi\build\celestial_navigation_pi.vcxproj]    `
(Also there are a lot of Nan and infinity warnings.)

I have checked all the pairs of brackets in the file, compared it to earlier files and have tried to save it with a feature "trim trailing spaces".  I can't figure out what the problem is.  It won't build locally, but I am going to push it up to github.

https://github.com/rgleason/celestial_navigation_pi    Master branch

[output.txt](https://github.com/rgleason/celestial_navigation_pi/files/7444402/output.txt)

If you have any other thoughts about this I would be very interested.

**Comment by bdbcat** [comment]
Rick...
typo in CelestialNavigationDialog.cpp:424 
is:
   m_lSights->SetItem(idx, rmTYPE, SightType[s->m_Type]);
should be:
   m_lSights->SetItem(idx, rmTYPE, SightType([s->m_Type]);

Note added "(".

**Comment by rgleason** [comment]
Dave,

    m_lSights->SetItem(idx, rmTYPE, SightType([s->m_Type]));

You are very kind to put up with the likes of me, with eyesight getting worse, an old hack, etc.

Do I need another right bracket too?

Rick
PS: Sorry I emailed this too by mistake.

**Comment by bdbcat** [comment]
Rick...
Disregard previous suggestion.  Line 424 is fine as is.
1.  in CMakeLists.txt, correct spelling of zufile, should be zuFile, two places
2. in CelestialNavigationDialog.cpp, add  #endif after line 216:

**Comment by rgleason** [comment]
1. Done.
2.  The #endif   that is missing, seems to be part of   #ifdef __OCPN__ANDROID__
3.  So all of that code is for Android?  
4. Maybe I was sloppy and deleted or missed in copying, an #endif after 
```
. #ifdef __OCPN__ANDROID__
void CelestialNavigationDialog::OnEvtPanGesture( wxQT_PanGestureEvent &event)
{
    switch(event.GetState()){
        case GestureStarted:
            m_startPos = GetPosition();
            m_startMouse = event.GetCursorPos(); //g_mouse_pos_screen;
            break;
        default:
        {
            wxPoint pos = event.GetCursorPos();
            int x = wxMax(0, pos.x + m_startPos.x - m_startMouse.x);
            int y = wxMax(0, pos.y + m_startPos.y - m_startMouse.y);
            int xmax = ::wxGetDisplaySize().x - GetSize().x;
            x = wxMin(x, xmax);
            int ymax = ::wxGetDisplaySize().y - GetSize().y;          // Some fluff at the bottom
            y = wxMin(y, ymax);

            Move(x, y);
        } break;
    }
// master
}
LINE 217?   put  #endif   here?

```

around line 217

**Comment by rgleason** [comment]
I think I'll try that.

**Comment by rgleason** [comment]
Ok that seems to build further, don't know for sure if that is where the #endif goes.....

but the next hangup is  from zuFile   and I have seen this before,  unresolved external symbol gzopen, gzread, gzseek, gxtell, and gxclose

So something is wrong in my cmakelists.txt file

```
  geodesic.c
     Creating library C:/Users/fcgle/source/celestial_navigation_pi/build/Release/celestial_navigation_pi.lib and object C:/Users/fcgle/source/celestial_navigation_pi/build/Release/celestial_navigation_pi.exp
zuFile.obj : error LNK2019: unresolved external symbol _gzopen referenced in function _zu_open [C:\Users\fcgle\source\celestial_navigation_pi\build\celestial_navigation_pi.vcxproj]
zuFile.obj : error LNK2019: unresolved external symbol _gzread referenced in function _zu_read [C:\Users\fcgle\source\celestial_navigation_pi\build\celestial_navigation_pi.vcxproj]
zuFile.obj : error LNK2019: unresolved external symbol _gzseek referenced in function _zu_rewind [C:\Users\fcgle\source\celestial_navigation_pi\build\celestial_navigation_pi.vcxproj]
zuFile.obj : error LNK2019: unresolved external symbol _gztell referenced in function _zu_rewind [C:\Users\fcgle\source\celestial_navigation_pi\build\celestial_navigation_pi.vcxproj]
zuFile.obj : error LNK2019: unresolved external symbol _gzclose referenced in function _zu_can_read_file [C:\Users\fcgle\source\celestial_navigation_pi\build\celestial_navigation_pi.vcxproj]
C:\Users\fcgle\source\celestial_navigation_pi\build\Release\celestial_navigation_pi.dll : fatal error LNK1120: 5 unresolved externals [C:\Users\fcgle\source\celestial_navigation_pi\build\celestial_navigation_pi.vcxproj]

```

**Comment by rgleason** [comment]
Those are located in zlib  and we have  zlib-1.2.3  in the libs/ folder, but there are no cpp files!
https://www.zlib.net/  has  zlib 1.2.11  from 2017  do I dare download and use that?

**Comment by rgleason** [comment]
I checked back in the frontend2 branch and did not find these libraries were being used. 
I don't know why we are being forced down this road of adding libraries that were not there.
Indeed frontend2 built fine, but without some of the more recent if androids.

I did find that Sean had added android UI and had fixed the database for android 
see  https://github.com/rgleason/celestial_navigation_pi/commit/89fef0eb6f5ac4d3a811cef84309ce12cc47a892#diff-41f953ddfbd947912eec708c84fc4a9bfdce02acea05dd66e86d034e141f51cd

And in that same area he changed the db to work with android, so android has been around for some time...

**Comment by rgleason** [comment]
Do you think I should just update the library to zlib 1.2.11  ?

**Comment by bdbcat** [comment]
No.  This is a rathole.
Revert back to before Android, and drop Android for now.
I cannot help you now. Later days....

**Comment by rgleason** [comment]
Ok, I agree totally.   I will revert it.    But as I wrote earlier,[ android has been in this plugin a long time](https://github.com/rgleason/celestial_navigation_pi/issues/14#issuecomment-955315796)
However, I think I still need the getpPrivateDataLocation addition to be compatible with the new PIM standard for data location.

BTW I found  https://zlib.net/fossils/  with zlib-1.2.3 it is just500kb but many files, and I determined that weather_routing (which is where I got zlib-1.2.3) just has the two header files and no cpp.

**Comment by rgleason** [comment]
1. In celestialnavigtiondialog.cpp at the top commented out the one Android UI addition towards the top and left the getpPriCommented out the #include  zuFile.h vateDataLocation code at the top
2. In cmakelists.txt  Removed references to zuFile.h and zuFile.cpp in SRC and HDRS also commented out the include dir for zlib-1.2.3  
Now it seems to build. I will check whether it works and clean up.

Thanks

**Comment by rgleason** [comment]
I had to try it after learning more, I uncommented the one AndroidUI command at the top of cel_navdialog.cpp and then ran a build and it completed!   The include zuFile.h is still commented out, so that was the problem, I think I am going to remove that commented out line completely and all the excess files/libs and cmakelists.txt refs. to clean up.

Will test and see what happens.

**Comment by rgleason** [comment]
Cleaned up and working in Win10, will push
