### ISSUE TITLE
GetpPrivateApplicationDataLocation  issue

### ISSUE THREAD

**Issue by rgleason** [rgleason/celestial_navigation_pi#7]
As there is no way to write issues for the celestial_navigation_pi plugin, and knowing that you develop it too, I inform you that the same problem exists for it
to obtain that celestial_navigation create the good path inside flatpak :
/home/yourusername/.var/app/org.opencpn.OpenCPN/config/opencpn/plugins/ celestial_navigation
where to store the personnal writeable Sights.xml file

**Comment by filochard** [comment]
I may add that installing celestial_navigation plugin inside flatpak with the plugin manager doesn't work well
There's no icon created in the icons tray
Worse when you install it
![screen_20210519-184739](https://user-images.githubusercontent.com/16304019/118852628-3adb6880-b8d3-11eb-979c-451683e2b5bc.png)
you get this
![screen_20210519-184935](https://user-images.githubusercontent.com/16304019/118852682-47f85780-b8d3-11eb-8e71-eb3e43b3420a.png)
you apply and say OK
no icon
But if you stop opencpn and restart it
you get this again
![screen_20210519-184739](https://user-images.githubusercontent.com/16304019/118852860-7118e800-b8d3-11eb-880c-282f8938344d.png)

The same problem occurs with radar
https://github.com/opencpn-radar-pi/radar_pi/issues/169

**Comment by leamas** [comment]
This one should now be possible to close. The data directory stuff is in #10, and the missing library causing @filochard 's  flatpak "does not work"  is fixed in #9.

**Comment by rgleason** [comment]
OK, thankyou!
